import type { Customer, Task, Visit } from './types'

export const initialVisits: Visit[] = [
  {
    id: 1,
    customer: '华东智造科技有限公司',
    shortName: '华',
    contact: '张经理',
    phone: '138****8888',
    owner: '张伟',
    participants: ['张伟', '李明'],
    date: '2026-09-04',
    time: '09:30',
    endTime: '10:30',
    location: '上海市浦东新区世纪大道100号',
    region: '上海市浦东新区',
    matter: '了解产线数字化现状，沟通设备管理平台实施范围与交付计划。',
    result: '客户认可一期方案，要求下周提交项目排期及正式报价。',
    status: '已完成',
    color: '#0d6efd',
  },
  {
    id: 2,
    customer: '上海优品贸易有限公司',
    shortName: '优',
    contact: '李总',
    phone: '136****2710',
    owner: '李明',
    participants: ['李明', '王佳'],
    date: '2026-09-04',
    time: '11:00',
    endTime: '12:00',
    location: '上海市静安区南京西路688号',
    region: '上海市静安区',
    matter: '季度合作复盘，确认国庆档促销资源与补货节奏。',
    result: '已完成初步资源确认，待补充渠道销售预测。',
    status: '进行中',
    color: '#16a36a',
  },
  {
    id: 3,
    customer: '苏州智造企业服务有限公司',
    shortName: '苏',
    contact: '王经理',
    phone: '139****5192',
    owner: '王佳',
    participants: ['王佳'],
    date: '2026-09-04',
    time: '14:00',
    endTime: '15:30',
    location: '苏州市工业园区星湖街328号',
    region: '苏州市工业园区',
    matter: '产品方案演示及采购需求澄清。',
    result: '待拜访后填写。',
    status: '待开始',
    color: '#8c6ad8',
  },
  {
    id: 4,
    customer: '杭州云创信息技术有限公司',
    shortName: '杭',
    contact: '陈经理',
    phone: '137****6320',
    owner: '陈超',
    participants: ['陈超', '张伟'],
    date: '2026-09-04',
    time: '16:00',
    endTime: '17:00',
    location: '杭州市滨江区江南大道588号',
    region: '杭州市滨江区',
    matter: '售后问题回访并确认二期接口清单。',
    result: '待拜访后填写。',
    status: '待开始',
    color: '#ee8a21',
  },
  {
    id: 7,
    customer: '嘉兴启航新材料有限公司',
    shortName: '嘉',
    contact: '赵经理',
    phone: '133****8621',
    owner: '刘总',
    participants: ['刘总', '王佳'],
    date: '2026-09-04',
    time: '17:30',
    endTime: '18:20',
    location: '嘉兴市南湖区亚太路778号',
    region: '嘉兴市南湖区',
    matter: '确认新材料试用反馈及下一批采购计划。',
    result: '待拜访后填写。',
    status: '待开始',
    color: '#596bc8',
  },
  {
    id: 8,
    customer: '无锡领创自动化有限公司',
    shortName: '锡',
    contact: '顾经理',
    phone: '131****5407',
    owner: '张伟',
    participants: ['张伟'],
    date: '2026-09-04',
    time: '19:00',
    endTime: '19:45',
    location: '无锡市新吴区菱湖大道200号',
    region: '无锡市新吴区',
    matter: '远程回访自动化改造项目运行情况。',
    result: '待拜访后填写。',
    status: '待开始',
    color: '#0f8ca8',
  },
  {
    id: 5,
    customer: '南京聚力电子有限公司',
    shortName: '南',
    contact: '周总',
    phone: '135****4056',
    owner: '刘总',
    participants: ['刘总', '李明'],
    date: '2026-09-05',
    time: '10:00',
    endTime: '11:00',
    location: '南京市雨花台区软件大道180号',
    region: '南京市雨花台区',
    matter: '年度框架合作意向沟通。',
    result: '待拜访后填写。',
    status: '待开始',
    color: '#0f8ca8',
  },
  {
    id: 6,
    customer: '宁波远航供应链有限公司',
    shortName: '宁',
    contact: '孙经理',
    phone: '132****1785',
    owner: '张伟',
    participants: ['张伟'],
    date: '2026-09-03',
    time: '15:00',
    endTime: '16:20',
    location: '宁波市鄞州区宁东路269号',
    region: '宁波市鄞州区',
    matter: '运输可视化项目需求确认。',
    result: '补充跨境线路数据后再次评估。',
    status: '已延期',
    color: '#dc5a5a',
  },
]

export const initialTasks: Task[] = [
  {
    id: 1,
    title: '提交华东智造项目排期及正式报价',
    customer: '华东智造科技有限公司',
    assignee: '张伟',
    due: '2026-09-04',
    dueLabel: '今天 17:30',
    priority: '高',
    status: '进行中',
    source: '9月4日客户拜访',
  },
  {
    id: 2,
    title: '补充优品贸易渠道销售预测表',
    customer: '上海优品贸易有限公司',
    assignee: '李明',
    due: '2026-09-05',
    dueLabel: '明天 12:00',
    priority: '中',
    status: '待处理',
    source: '9月4日客户拜访',
  },
  {
    id: 3,
    title: '准备苏州智造产品演示环境',
    customer: '苏州智造企业服务有限公司',
    assignee: '王佳',
    due: '2026-09-04',
    dueLabel: '今天 13:00',
    priority: '高',
    status: '已逾期',
    source: '拜访准备',
  },
  {
    id: 4,
    title: '确认杭州云创二期接口清单',
    customer: '杭州云创信息技术有限公司',
    assignee: '陈超',
    due: '2026-09-06',
    dueLabel: '9月6日',
    priority: '中',
    status: '待处理',
    source: '项目跟进',
  },
  {
    id: 5,
    title: '整理八月部门客户拜访周报',
    customer: '部门内部',
    assignee: '张伟',
    due: '2026-09-03',
    dueLabel: '逾期 1 天',
    priority: '低',
    status: '已逾期',
    source: '独立待办',
  },
  {
    id: 6,
    title: '更新南京聚力年度合作建议书',
    customer: '南京聚力电子有限公司',
    assignee: '李明',
    due: '2026-09-07',
    dueLabel: '9月7日',
    priority: '中',
    status: '已完成',
    source: '客户跟进',
  },
]

export const customers: Customer[] = [
  {
    id: 1,
    name: '华东智造科技有限公司',
    shortName: '华',
    industry: '智能制造',
    contact: '张经理',
    phone: '138****8888',
    region: '上海 · 浦东新区',
    owner: '张伟',
    lastVisit: '今天 09:30',
    nextAction: '提交项目排期及报价',
    openTasks: 2,
    status: '重点跟进',
    color: '#0d6efd',
  },
  {
    id: 2,
    name: '上海优品贸易有限公司',
    shortName: '优',
    industry: '商贸零售',
    contact: '李总',
    phone: '136****2710',
    region: '上海 · 静安区',
    owner: '李明',
    lastVisit: '今天 11:00',
    nextAction: '补充渠道销售预测',
    openTasks: 1,
    status: '正常',
    color: '#16a36a',
  },
  {
    id: 3,
    name: '苏州智造企业服务有限公司',
    shortName: '苏',
    industry: '企业服务',
    contact: '王经理',
    phone: '139****5192',
    region: '苏州 · 工业园区',
    owner: '王佳',
    lastVisit: '8月26日',
    nextAction: '今日产品方案演示',
    openTasks: 3,
    status: '重点跟进',
    color: '#8c6ad8',
  },
  {
    id: 4,
    name: '杭州云创信息技术有限公司',
    shortName: '杭',
    industry: '软件信息',
    contact: '陈经理',
    phone: '137****6320',
    region: '杭州 · 滨江区',
    owner: '陈超',
    lastVisit: '8月18日',
    nextAction: '确认二期接口清单',
    openTasks: 1,
    status: '正常',
    color: '#ee8a21',
  },
  {
    id: 5,
    name: '南京聚力电子有限公司',
    shortName: '南',
    industry: '电子科技',
    contact: '周总',
    phone: '135****4056',
    region: '南京 · 雨花台区',
    owner: '刘总',
    lastVisit: '7月30日',
    nextAction: '年度框架合作沟通',
    openTasks: 1,
    status: '正常',
    color: '#0f8ca8',
  },
  {
    id: 6,
    name: '宁波远航供应链有限公司',
    shortName: '宁',
    industry: '物流供应链',
    contact: '孙经理',
    phone: '132****1785',
    region: '宁波 · 鄞州区',
    owner: '张伟',
    lastVisit: '8月12日',
    nextAction: '补充跨境线路数据',
    openTasks: 0,
    status: '待激活',
    color: '#dc5a5a',
  },
]

export const weeklyPerformance = [
  { day: '周一', date: '8/31', planned: 8, completed: 6 },
  { day: '周二', date: '9/1', planned: 11, completed: 9 },
  { day: '周三', date: '9/2', planned: 9, completed: 8 },
  { day: '周四', date: '9/3', planned: 13, completed: 10 },
  { day: '周五', date: '9/4', planned: 12, completed: 6 },
  { day: '周六', date: '9/5', planned: 5, completed: 0 },
  { day: '周日', date: '9/6', planned: 3, completed: 0 },
]

export const departmentRanking = [
  { name: '张伟', visits: 12, tasks: 18, rate: 92 },
  { name: '李明', visits: 10, tasks: 15, rate: 88 },
  { name: '王佳', visits: 9, tasks: 14, rate: 86 },
  { name: '陈超', visits: 8, tasks: 12, rate: 83 },
]
